
ifeq ($(SYSTEM), csd3-intel20)
    FC= mpiifort
    FFLAGS= -O3 -mavx2 -mfma -mcmodel=medium \
            -warn uninitialized -warn truncated_source\
            -warn interfaces -nogen-interfaces -DINCMPI -march=icelake-server
# -check_mpi
    OMPFLAG= -qopenmp
    DBLFLAG= -r8
    DEBUGFLAG= -check all -traceback -g -fpe0 -fp-stack-check -heap-arrays -O0
    KNOWN_SYSTEM=yes
    ENDIANFLAGBIG= -convert big_endian
    ENDIANFLAGLITTLE= -convert little_endian
    IPOFLAG=
# or use setenv F_UFMTENDIAN=big:45 at runtime (e.g. for unit 45 only)
    ZZFILE= zzibm.f
endif
